name: Test420

on:
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    
    permissions:
      contents: read
      
    steps:
      - run: cat "$GITHUB_EVENT_PATH"
      - run: gh --version
      
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: actions/attest-build-provenance@c4fbc648846ca6f503a13a2281a5e7b98aa57202 # v2.0.1
        with:
          subject-path: '${{ github.workspace }}'
