name: Test417

on:
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    
    permissions:
      contents: read
      
    steps:
      - run: cat "$GITHUB_EVENT_PATH"
      - run: gh --version
      
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
