name: Test2

on:
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    
    permissions:
      contents: read
      
    steps:
      - run: cat "$GITHUB_EVENT_PATH"
      - run: gh --version
      
      - uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
        with:
          subject-path: '${{ github.workspace }}'
