name: Test1

on:
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    
    permissions:
      contents: read
      
    steps:
      - run: cat "$GITHUB_EVENT_PATH"
      - run: gh --version
      
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
